In [1]:
import pandas as pd
import numpy as np 
from sklearn import linear_model

In [57]:
df= pd.read_csv('MFG10YearTerminationData.csv', usecols= [0,5,6,10], index_col=None )

In [58]:
df

EmployeeID  age  length_of_service  store_name
0            1318   52                 17          35
1            1318   53                 18          35
2            1318   54                 19          35
3            1318   55                 20          35
4            1318   56                 21          35
...           ...  ...                ...         ...
49648        8258   21                  2          34
49649        8264   19                  0          44
49650        8279   21                  2          39
49651        8296   19                  0          16
49652        8321   20                  1          13

[49653 rows x 4 columns]

In [59]:
df.isnull().sum()

EmployeeID           0
age                  0
length_of_service    0
store_name           0
dtype: int64

In [60]:
df.length_of_service.iloc[5] = None

In [61]:
df.length_of_service.isnull().sum()

1

In [62]:
median_value =df.length_of_service.median()

In [63]:
median_value

10.0

In [64]:
df.length_of_service.fillna(median_value, inplace= True)

In [65]:
df.length_of_service.isnull().sum()

0

In [66]:
df

EmployeeID  age  length_of_service  store_name
0            1318   52               17.0          35
1            1318   53               18.0          35
2            1318   54               19.0          35
3            1318   55               20.0          35
4            1318   56               21.0          35
...           ...  ...                ...         ...
49648        8258   21                2.0          34
49649        8264   19                0.0          44
49650        8279   21                2.0          39
49651        8296   19                0.0          16
49652        8321   20                1.0          13

[49653 rows x 4 columns]

In [67]:
data = df[: 41]

In [68]:
data

EmployeeID  age  length_of_service  store_name
0         1318   52               17.0          35
1         1318   53               18.0          35
2         1318   54               19.0          35
3         1318   55               20.0          35
4         1318   56               21.0          35
5         1318   57               10.0          35
6         1318   58               23.0          35
7         1318   59               24.0          35
8         1318   60               25.0          35
9         1318   61               26.0          35
10        1319   49               17.0          35
11        1319   50               18.0          35
12        1319   51               19.0          35
13        1319   52               20.0          35
14        1319   53               21.0          35
15        1319   54               22.0          35
16        1319   55               23.0          35
17        1319   56               24.0          35
18        1319   57               25.0          35
19        1319   58               26.0          35
20        1320   51               17.0          35
21        1320   52               18.0          35
22        1320   53               19.0          35
23        1320   54               20.0          35
24        1320   55               21.0          35
25        1320   56               22.0          35
26        1320   57               23.0          35
27        1320   58               24.0          35
28        1320   59               25.0          35
29        1320   60               26.0          35
30        1321   47               17.0          35
31        1321   48               18.0          35
32        1321   49               19.0          35
33        1321   50               20.0          35
34        1321   51               21.0          35
35        1321   52               22.0          35
36        1321   53               23.0          35
37        1321   54               24.0          35
38        1321   55               25.0          35
39        1321   56               26.0          35
40        1322   48               17.0          35

In [70]:
linear = linear_model.LinearRegression()

In [71]:
# df.department_name.astype('int')

In [73]:
linear.fit(df[['EmployeeID','age','length_of_service']], df.store_name)

LinearRegression()

In [74]:
linear.coef_

array([-0.0005426 , -0.14270163,  0.13914439])

In [75]:
linear.intercept_

34.48696411188755

In [78]:
linear.predict([[1325,45,15]])

C:\Users\vishn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([29.43360723])

In [82]:
# for i in df.age:
#     if i >=40:
#         print(df['age'])

In [85]:
# the caluations 
x=(-0.0005426*1325 + -0.14270163 *45 + 0.13914439* 15 ) + 34.48696411188755

In [86]:
x

29.433611611887553

In [87]:
# linear.predict([[1325,45,15]]) and x is similar

## Excercise using HR data

In [140]:
data = pd.read_csv('hiring.csv')

In [141]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [142]:
data.rename(columns= { 'test_score(out of 10)' : 'testscore',
                      'interview_score(out of 10)' : 'interview_score' ,
                      'salary($)' : 'salary' }, inplace= True)

In [143]:
missing = data.testscore.median()

In [144]:
data.testscore.fillna(missing, inplace=True)

In [145]:
data

experience  testscore  interview_score  salary
0        NaN        8.0                9   50000
1        NaN        8.0                6   45000
2       five        6.0                7   60000
3        two       10.0               10   65000
4      seven        9.0                6   70000
5      three        7.0               10   62000
6        ten        8.0                7   72000
7     eleven        7.0                8   80000

In [146]:
# def replace_values(x):
#     if x=='NaN':
#         x=0
#         return x

In [147]:
data.experience.fillna('zero', inplace= True)

In [148]:
data

experience  testscore  interview_score  salary
0       zero        8.0                9   50000
1       zero        8.0                6   45000
2       five        6.0                7   60000
3        two       10.0               10   65000
4      seven        9.0                6   70000
5      three        7.0               10   62000
6        ten        8.0                7   72000
7     eleven        7.0                8   80000

In [133]:
# pip install word2num

   ---------------------------------------- 0.0/98.4 kB ? eta -:--:--
   ------------ --------------------------- 30.7/98.4 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 98.4/98.4 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.7 MB 3.6 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.7 MB 2.8 MB/s eta 0:00:01
   ---------- ----------------------------- 0.5/1.7 MB 2.4 MB/s eta 0:00:01
   ------------ --------------------------- 0.5/1.7 MB 2.2 MB/s eta 0:00:01
   --------------- ------------------------ 0.6/1.7 MB 2.4 MB/s eta 0:00:01
   ----------------- ---------------------- 0.7/1.7 MB 2.2 MB/s eta 0:00:01
   ------------------- -------------------- 0.8/1.7 MB 2.2 MB/s eta 0:00:01
   --------------------- ------------------ 0.9/1.7 MB 2.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.7 MB 2.1 MB/s eta 0:00:01
   ------------------


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [134]:
# pip install word2number



  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5589 sha256=40393fe59f2406c638d855654be2b490cef1ae12f77ee6208391c0435ab98b3a
  Stored in directory: c:\users\vishn\appdata\local\pip\cache\wheels\cd\ef\ae\073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [149]:
from word2number import w2n

In [151]:
data

experience  testscore  interview_score  salary
0       zero        8.0                9   50000
1       zero        8.0                6   45000
2       five        6.0                7   60000
3        two       10.0               10   65000
4      seven        9.0                6   70000
5      three        7.0               10   62000
6        ten        8.0                7   72000
7     eleven        7.0                8   80000

In [152]:
data['Experience'] = w2n.word_to_num(data['experience'])

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [155]:
data['experience'] = data.experience.apply(w2n.word_to_num,)

In [156]:
data

experience  testscore  interview_score  salary
0           0        8.0                9   50000
1           0        8.0                6   45000
2           5        6.0                7   60000
3           2       10.0               10   65000
4           7        9.0                6   70000
5           3        7.0               10   62000
6          10        8.0                7   72000
7          11        7.0                8   80000

In [157]:
from sklearn.linear_model import LinearRegression

In [158]:
reg= LinearRegression()

In [160]:
reg.fit(data[['experience', 'testscore', 'interview_score']], data.salary)

LinearRegression()

### Here we use the exitsing value to test the accuracy of the model 

[https://machinelearningmastery.com/regression-metrics-for-machine-learning/]

### Used two metrics 
1. mean_absoule_error
2. mean_squared_error

In [165]:
reg.predict([[5,6,7]])

C:\Users\vishn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([58312.95487627])

In [172]:
from sklearn.metrics import accuracy_score, mean_squared_error, mean_absolute_error
y_test= [[60000]]
y_pred = [[58312.95487627]]
mae= mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred,squared=False)
mse

# accu =accuracy_score(y_test, y_pred)

C:\Users\vishn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


1687.0451237300003

In [171]:
mae

1687.0451237300003

## The error is less and satisfactory to the model so we can proceed furthur, there are no model with 0 errors, if exits its a trivial....

### Trying out for the values 

In [163]:
reg.predict([[2,9,6]])

C:\Users\vishn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [164]:
reg.predict([[12,10,10]])

C:\Users\vishn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])